# Generated by Django 5.2.2 on 2025-06-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trajet',
            options={'ordering': ['-date_depart'], 'verbose_name': 'Trajet', 'verbose_name_plural': 'Trajets'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='contact_whatsapp',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nom',
            field=models.CharField(default='Anonyme', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='telephone',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='kilos_disponibles',
            field=models.IntegerField(),
        ),
    ]
