# Generated by Django 5.2.2 on 2025-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_trajet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='kilos',
            field=models.FloatField(),
        ),
    ]
